### ISSUE TITLE
Design how various new elements should fit into the design of MP pages

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#540]
MP pages have a few thing missing, and I'd like them adding as a harmonious whole, rather than a rag-bag of fixes:
- <del>The dates when an MP joined/left</del> #446
- [x] The mini survey #447 
- [x] Where the data comes from #504 
- [x] Signposting external links #505 
- [x] MP's current position #449 
- [x] Give more prominence to "former" positions #528
- <del>Any info where they changed party</del> #441 
- [x] How longer names should look #444 
- [x] Space for 'recent votes' data #551

This ticket relates to getting the overall design right for all of these elements - then implementing the designs can be done by people working on one ticket at a time.
