### ISSUE TITLE
Improve Email Alerts (high level ticket)

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/theyworkforyou#593]
This needs to cover:
- [ ] 1 - Improving the experience of unsubscribing - #737 
- [ ] 2 - Improving the experience of subscribing to an MP's updates from an MP page
- [ ] 3 - Improving the experience of subscribing for keyword alerts (get designers to suggest whole journey here)
- [x] 4 - Stop people subscribing to alerts based on postcodes actually being mentioned in parliament
- [x] 5 - Stop people subscribing to alerts based on when a person's name is mentioned in parliament
- [ ] 6 - Improve the experience of modifying a user's current email alerts (plural)
- [x] 7 - Improve the layout of the emails themselves #277 #251
- [ ] 8 - Improve the experience of signing people up to multiple keyword alerts #24

**Comment by struan** [comment]
Related: #737
